version: "2"
services:
  db:
    image: postgres:16
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
    ports:
      - "${DB_PORT}:5432"
  # web:
  #   build: .
  #   command: bash -c "bundle install && bundle exec puma"
  #   volumes:
  #     - .:/myapp
  #     - bundle_cache:/usr/local/bundle
  #   ports:
  #     - "${WEB_PORT}:3000"
  #   depends_on:
  #     - db

volumes:
  bundle_cache:
